version:          "0028a--05-Feb-2024"
copyright:        "2021-2024"
title:            "SP241: Why Jekyll?"
author:           "F. F. Yusuf"
address:          "Ponyville, Equestria"
description:
  Welcome to my page for SP241! 
  This page will contain all of my inner working of my mind
  related to System Programming Class. 
disclaimer:
  This site contains ponies.
tagline:          "This is a GitHub Page Template tagline"
keywords:         "jekyll, sp241, sp241-site, fawzan"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "Tips"
  link:           "/TIPS/"
- navbar:         "Zip File"
  link:           "/template.zip"
- navbar:         "TarBall"
  link:           "/template.tar.xz"
- navbar:         "GitHub"
  link:           "https://github.com/fawzakin"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "Source"
  link:           "https://github.com/fawzakin/sp241-site"
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://template.vlsm.org/"
urlcontact:       "no"
urlgithub:        "https://github.com/yforku/template/"
google_analytics: "Please Don't"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
